modLoader="javafml"
loaderVersion="[35,)"
license="Creative Commons"

[[mods]]
modId="farmadditions"
version="1.0.0"
displayName="Farm Additions"
credits="Thanks to Avalon Team and my Twitter Followers."
authors="Avalon Team."
description='''
Explore new biomes, find new plants, craft some new food, 
welcome to Avalon Mods: Farm Additions!
In this first update the principal atracttion is 
Galimea Enderlands, a new End biome to explore and find
it secrets.
'''